"use client";

import { useEffect, useRef, useState } from "react";
import type { PlayableGameProps } from "../types";
import { createRandom } from "../random";

const text = (locale: PlayableGameProps["locale"], en: string, zh: string) => locale === "en" ? en : zh;
type Cell = { row: number; col: number };
type Rect = { top: number; left: number; bottom: number; right: number };
export function rectFromPoints(a: Cell, b: Cell): Rect { return { top: Math.min(a.row,b.row), left: Math.min(a.col,b.col), bottom: Math.max(a.row,b.row), right: Math.max(a.col,b.col) }; }
function inRect(rect: Rect | null, row: number, col: number) { return Boolean(rect && row >= rect.top && row <= rect.bottom && col >= rect.left && col <= rect.right); }

export function GardenGame(props: PlayableGameProps) {
  switch (props.slug) {
    case "sum-orchard": return <SumOrchard {...props} />;
    case "color-cross": return <ColorCross {...props} />;
    case "orbit-lines": return <OrbitLines {...props} />;
    case "corner-stars": return <CornerStars {...props} />;
    case "sidefall-blocks": return <SidefallBlocks {...props} />;
    case "triad-capture": return <TriadCapture {...props} />;
    case "echo-path": return <EchoPath {...props} />;
    case "target-basket": return <TargetBasket {...props} />;
    case "math-grid-sprint": return <MathGridSprint {...props} />;
    default: return null;
  }
}

function useTimer(initial: number, paused: boolean, resetKey: number, onExpire: () => void) {
  const [time, setTime] = useState(initial);
  const expireRef = useRef(onExpire);
  useEffect(() => { expireRef.current = onExpire; }, [onExpire]);
  useEffect(() => { setTime(initial); }, [initial, resetKey]);
  useEffect(() => { if (paused) return; const id = window.setInterval(() => setTime((value) => { if (value <= 1) { window.clearInterval(id); queueMicrotask(() => expireRef.current()); return 0; } return value - 1; }), 1000); return () => window.clearInterval(id); }, [paused, resetKey]);
  return [time, setTime] as const;
}

function generateSumBoard() { const random=createRandom(); const board:(number|null)[][]=Array.from({length:8},()=>Array.from({length:12},()=>random.int(1,9))); const planted=[[0,0,5,7],[1,4,4,8],[3,2,3,9],[5,8,6,6],[7,5,1,11]]; for(const [r,c,a,b] of planted){board[r][c]=a;board[r][c+1]=b;} return board; }
export function sumRect(board:(number|null)[][],rect:Rect){let sum=0,count=0;for(let r=rect.top;r<=rect.bottom;r++)for(let c=rect.left;c<=rect.right;c++)if(board[r][c]!==null){sum+=board[r][c]!;count++;}return{sum,count};}
function hasSumMove(board:(number|null)[][]){for(let r=0;r<8;r++)for(let c=0;c<12;c++){if(board[r][c]===12)return true;if(c<11&&(board[r][c]??0)+(board[r][c+1]??0)===12)return true;if(r<7&&(board[r][c]??0)+(board[r+1][c]??0)===12)return true;}return false;}

function SumOrchard(props:PlayableGameProps){const [board,setBoard]=useState(generateSumBoard);const [anchor,setAnchor]=useState<Cell|null>(null);const [score,setScore]=useState(0);const [time,setTime]=useTimer(90,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setBoard(generateSumBoard());setAnchor(null);setScore(0);props.onScore(0);},[props.resetKey]);function choose(row:number,col:number){if(props.paused)return;if(!anchor){setAnchor({row,col});props.onStatus(text(props.locale,"Selection started","已开始框选"));return;}const rect=rectFromPoints(anchor,{row,col});const result=sumRect(board,rect);setAnchor(null);if(result.sum!==12||!result.count){props.onStatus(text(props.locale,`Selection total: ${result.sum}`,`框选总和：${result.sum}`));return;}const next=board.map(items=>[...items]);for(let r=rect.top;r<=rect.bottom;r++)for(let c=rect.left;c<=rect.right;c++)next[r][c]=null;const points=result.count*2+(result.count===1?4:0);const total=score+points;setScore(total);props.onScore(total);props.sound("score");if(!hasSumMove(next)){setBoard(generateSumBoard());setTime(value=>value+5);props.onStatus(text(props.locale,"Board cleared — 5 second bonus","棋盘已更新，奖励 5 秒"));}else{setBoard(next);props.onStatus(text(props.locale,`${result.count} fruit harvested`,`收获了 ${result.count} 个数字果实`));}}const live=anchor?rectFromPoints(anchor,anchor):null;return <div className="logic-game garden-game"><GardenHud locale={props.locale} target="12" time={time} extra={text(props.locale,"Select two corners","选择矩形的两个角")}/><div className="garden-grid sum-grid" role="grid">{board.flatMap((row,r)=>row.map((value,c)=><button role="gridcell" key={`${r}-${c}`} className={`${value===null?"empty":"fruit-cell"} ${inRect(live,r,c)?"selected":""}`} onClick={()=>choose(r,c)} aria-label={`${r+1}, ${c+1}: ${value??text(props.locale,"empty","空")}`}>{value}</button>))}</div>{anchor&&<button className="logic-secondary" onClick={()=>setAnchor(null)}>{text(props.locale,"Cancel selection","取消框选")}</button>}</div>}

function colorCrossBoard(){const random=createRandom();const board:(number|null)[][]=Array.from({length:10},()=>Array(10).fill(null));for(let i=0;i<38;i++){const r=random.int(0,9),c=random.int(0,9);board[r][c]=random.int(0,3);}board[4][2]=1;board[4][7]=1;board[2][5]=2;board[8][5]=2;board[4][5]=null;return board;}
function nearest(board:(number|null)[][],r:number,c:number,dr:number,dc:number){for(let rr=r+dr,cc=c+dc;rr>=0&&rr<10&&cc>=0&&cc<10;rr+=dr,cc+=dc)if(board[rr][cc]!==null)return[rr,cc] as const;return null;}
function ColorCross(props:PlayableGameProps){const [board,setBoard]=useState(colorCrossBoard);const [score,setScore]=useState(0);const [streak,setStreak]=useState(0);const [time,setTime]=useTimer(90,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setBoard(colorCrossBoard());setScore(0);setStreak(0);props.onScore(0);},[props.resetKey]);function choose(r:number,c:number){if(props.paused||board[r][c]!==null)return;const left=nearest(board,r,c,0,-1),right=nearest(board,r,c,0,1),up=nearest(board,r,c,-1,0),down=nearest(board,r,c,1,0);const pairs:[readonly[number,number],readonly[number,number]][]=[];if(left&&right&&board[left[0]][left[1]]===board[right[0]][right[1]])pairs.push([left,right]);if(up&&down&&board[up[0]][up[1]]===board[down[0]][down[1]])pairs.push([up,down]);if(!pairs.length){setTime(value=>Math.max(0,value-4));setStreak(0);props.onStatus(text(props.locale,"No matching pair — 4 seconds","没有匹配对，扣除 4 秒"));props.sound("fail");return;}const next=board.map(row=>[...row]);for(const pair of pairs)for(const [rr,cc] of pair)next[rr][cc]=null;const removed=pairs.length*2;const nextStreak=streak+1;const points=Math.round((removed*3+(pairs.length===2?8:0))*(nextStreak>=4?1.5:1));const total=score+points;setBoard(next);setScore(total);setStreak(nextStreak);props.onScore(total);props.sound("score");props.onStatus(pairs.length===2?text(props.locale,"Cross bonus","获得十字奖励"):text(props.locale,"Matching pair cleared","匹配对已消除"));}return <div className="logic-game garden-game"><GardenHud locale={props.locale} target={text(props.locale,"Match opposite symbols","匹配相对符号")} time={time} extra={`${text(props.locale,"Streak","连击")} ${streak}`}/><div className="garden-grid cross-grid">{board.flatMap((row,r)=>row.map((value,c)=><button key={`${r}-${c}`} className={value===null?"cross-empty":`symbol-${value}`} onClick={()=>choose(r,c)} aria-label={`${r+1}, ${c+1}: ${value===null?text(props.locale,"empty","空位"):symbols[value]}`}>{value===null?"":symbols[value]}</button>))}</div></div>}

const symbols=["●","◆","▲","✚"];
function orbitBoard(){const board:(number|null)[][]=Array.from({length:8},()=>Array(8).fill(null));const random=createRandom();for(let i=0;i<24;i++){let r=random.int(0,7),c=random.int(0,7);while(board[r][c]!==null){r=random.int(0,7);c=random.int(0,7);}board[r][c]=random.int(0,3);}board[3][0]=0;board[3][3]=0;board[3][7]=0;return board;}
function straightPath(a:Cell,b:Cell){const dr=Math.sign(b.row-a.row),dc=Math.sign(b.col-a.col);if(!(dr===0||dc===0||Math.abs(b.row-a.row)===Math.abs(b.col-a.col)))return null;const path:Cell[]=[];for(let r=a.row+dr,c=a.col+dc;r!==b.row||c!==b.col;r+=dr,c+=dc)path.push({row:r,col:c});return path;}
function OrbitLines(props:PlayableGameProps){const [board,setBoard]=useState(orbitBoard);const [selected,setSelected]=useState<Cell|null>(null);const [score,setScore]=useState(0);const [time,setTime]=useTimer(110,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setBoard(orbitBoard());setSelected(null);setScore(0);props.onScore(0);},[props.resetKey]);function choose(row:number,col:number){if(props.paused)return;if(board[row][col]!==null){setSelected({row,col});return;}if(!selected)return;const path=straightPath(selected,{row,col});if(!path||path.some(cell=>board[cell.row][cell.col]!==null)){props.onStatus(text(props.locale,"That ray is blocked","这条直线路径被阻挡"));return;}const next=board.map(items=>[...items]);const value=next[selected.row][selected.col];next[selected.row][selected.col]=null;next[row][col]=value;const remove=new Set<string>();let axes=0;for(const [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]){const line:[[number,number]]=[[row,col]];for(const sign of [-1,1])for(let rr=row+dr*sign,cc=col+dc*sign;rr>=0&&rr<8&&cc>=0&&cc<8;rr+=dr*sign,cc+=dc*sign){if(next[rr][cc]!==null&&next[rr][cc]!==value)break;if(next[rr][cc]===value)line.push([rr,cc]);}if(line.length>=3){axes++;for(const [rr,cc] of line)remove.add(`${rr}-${cc}`);}}for(const key of remove){const [rr,cc]=key.split("-").map(Number);next[rr][cc]=null;}const count=remove.size;const points=count?(count===3?6:count===4?10:count===5?16:count*4)+(axes>1?10:0):0;const total=score+points;setBoard(next);setSelected(null);setScore(total);props.onScore(total);if(!count)setTime(value=>Math.max(0,value-3));props.sound(count?"score":"move");props.onStatus(count?text(props.locale,`${count} signal orbs cleared`,`${count} 个信号球已消除`):text(props.locale,"Legal move — no line, 3 seconds","移动合法但未连线，扣除 3 秒"));}return <div className="logic-game garden-game"><GardenHud locale={props.locale} target={text(props.locale,"Align 3+ matching orbs","连成至少 3 个相同信号球")} time={time} extra={selected?text(props.locale,"Choose a straight destination","选择直线方向的空位"):text(props.locale,"Choose an orb","选择一个信号球")}/><div className="garden-grid orbit-grid">{board.flatMap((row,r)=>row.map((value,c)=><button key={`${r}-${c}`} onClick={()=>choose(r,c)} className={`${value===null?"empty":`symbol-${value}`} ${selected?.row===r&&selected.col===c?"selected":""}`} aria-label={`${r+1}, ${c+1}`}>{value===null?"":symbols[value]}</button>))}</div></div>}

type Star={row:number;col:number;symbol:number;active:boolean};
function starField(){const random=createRandom();const map=new Map<string,Star>();const plant=[[1,1,0],[1,3,0],[3,1,0],[5,5,1],[3,5,1],[5,7,1]];for(const [row,col,symbol] of plant)map.set(`${row}-${col}`,{row,col,symbol,active:true});while(map.size<46){const row=random.int(0,8),col=random.int(0,8);map.set(`${row}-${col}`,{row,col,symbol:random.int(0,3),active:true});}return[...map.values()];}
function validCorner(stars:Star[]){if(stars.length!==3||!stars.every(s=>s.symbol===stars[0].symbol))return null;for(let i=0;i<3;i++){const corner=stars[i],a=stars[(i+1)%3],b=stars[(i+2)%3];const va=[a.row-corner.row,a.col-corner.col],vb=[b.row-corner.row,b.col-corner.col];const la=va[0]**2+va[1]**2,lb=vb[0]**2+vb[1]**2;if(la===lb&&la>0&&va[0]*vb[0]+va[1]*vb[1]===0)return{corner,length:Math.round(Math.sqrt(la)),diagonal:va[0]!==0&&va[1]!==0||vb[0]!==0&&vb[1]!==0};}return null;}
function CornerStars(props:PlayableGameProps){const [stars,setStars]=useState(starField);const [selected,setSelected]=useState<string[]>([]);const [score,setScore]=useState(0);const [shuffle,setShuffle]=useState(0);const [time,setTime]=useTimer(90,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setStars(starField());setSelected([]);setScore(0);setShuffle(0);props.onScore(0);},[props.resetKey]);function choose(star:Star){const key=`${star.row}-${star.col}`;let next=selected.includes(key)?selected.filter(item=>item!==key):[...selected,key].slice(-3);setSelected(next);if(next.length===3){const chosen=next.map(item=>stars.find(s=>`${s.row}-${s.col}`===item)!);const valid=validCorner(chosen);if(valid){const points=6+valid.length*2+(valid.diagonal?5:0);const total=score+points;setScore(total);props.onScore(total);setStars(stars.map(s=>next.includes(`${s.row}-${s.col}`)?{...s,active:false}:s));setSelected([]);props.sound("score");props.onStatus(text(props.locale,"Right-angle constellation cleared","直角星座已消除"));}else{props.onStatus(text(props.locale,"The stars do not form an equal right angle","这些星点没有组成等臂直角"));}}}function shuffleBoard(){const cost=shuffle<2?5:9;setTime(v=>Math.max(0,v-cost));setShuffle(s=>s+1);setStars(starField());setSelected([]);}return <div className="logic-game garden-game"><GardenHud locale={props.locale} target={text(props.locale,"Choose 3 matching stars","选择 3 个相同星点")} time={time} extra={`${text(props.locale,"Shuffle cost","重排代价")} ${shuffle<2?5:9}s`}/><div className="star-field" role="grid">{Array.from({length:81},(_,i)=>{const row=Math.floor(i/9),col=i%9,star=stars.find(s=>s.row===row&&s.col===col&&s.active);return star?<button key={i} onClick={()=>choose(star)} className={`star symbol-${star.symbol} ${selected.includes(`${row}-${col}`)?"selected":""}`} aria-label={`${text(props.locale,"Star","星点")} ${row+1},${col+1}`}>{symbols[star.symbol]}</button>:<span key={i} />;})}</div><button className="logic-secondary" onClick={shuffleBoard}>{text(props.locale,"Shuffle stars","重新排列星点")}</button></div>}

function blockColumns(){const random=createRandom();return Array.from({length:8},(_,c)=>Array.from({length:4+(c%3)},()=>random.int(0,3)));}
function connectedGroup(columns:number[][],column:number,row:number){const value=columns[column][row],queue:[[number,number]]=[[column,row]],seen=new Set<string>();while(queue.length){const [c,r]=queue.pop()!;const key=`${c}-${r}`;if(seen.has(key)||columns[c]?.[r]!==value)continue;seen.add(key);for(const [nc,nr] of [[c-1,r],[c+1,r],[c,r-1],[c,r+1]])if(nc>=0&&nc<8&&nr>=0)queue.push([nc,nr]);}return seen;}
function SidefallBlocks(props:PlayableGameProps){const [columns,setColumns]=useState(blockColumns);const [source,setSource]=useState<number|null>(null);const [score,setScore]=useState(0);const [time,setTime]=useTimer(110,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setColumns(blockColumns());setSource(null);setScore(0);props.onScore(0);},[props.resetKey]);function choose(column:number){if(props.paused)return;if(source===null){if(columns[column].length)setSource(column);return;}if(source===column){setSource(null);return;}if(columns[column].length>=10)return;let next=columns.map(items=>[...items]);const moved=next[source].pop()!;next[column].push(moved);let chain=1,points=0;while(true){let found:Set<string>|null=null;for(let c=0;c<8&&!found;c++)for(let r=0;r<next[c].length;r++){const group=connectedGroup(next,c,r);if(group.size>=3){found=group;break;}}if(!found)break;points+=found.size===3?6*chain:found.size===4?10*chain:found.size===5?16*chain:found.size*4*chain;const removeByColumn=new Map<number,Set<number>>();for(const key of found){const[c,r]=key.split("-").map(Number);if(!removeByColumn.has(c))removeByColumn.set(c,new Set());removeByColumn.get(c)!.add(r);}for(const[c,rows]of removeByColumn)next[c]=next[c].filter((_,r)=>!rows.has(r));chain++;}if(!points)setTime(v=>Math.max(0,v-3));const total=score+points;setColumns(next);setSource(null);setScore(total);props.onScore(total);props.sound(points?"score":"move");props.onStatus(points?text(props.locale,`Chain ×${chain-1}`,`连锁 ×${chain-1}`):text(props.locale,"No clear — 3 seconds","没有消除，扣除 3 秒"));}return <div className="logic-game garden-game"><GardenHud locale={props.locale} target={text(props.locale,"Move an exposed top block","移动每列顶部方块")} time={time} extra={source===null?text(props.locale,"Choose a stack","选择一列"):text(props.locale,"Choose a destination","选择目标列")}/><div className="column-board">{columns.map((column,c)=><button key={c} onClick={()=>choose(c)} className={source===c?"selected":""} aria-label={`${text(props.locale,"Column","列")} ${c+1}`}>{Array.from({length:10},(_,slot)=>{const value=column[9-slot];return <i key={slot} className={value===undefined?"":`symbol-${value}`}>{value===undefined?"":symbols[value]}</i>;})}</button>)}</div></div>}

function triadBoard(){const random=createRandom();const board:(number|null)[][]=Array.from({length:9},()=>Array.from({length:9},()=>random.int(0,2)));board[0][0]=0;board[0][1]=1;board[0][2]=2;return board;}
function TriadCapture(props:PlayableGameProps){const [board,setBoard]=useState(triadBoard);const [anchor,setAnchor]=useState<Cell|null>(null);const [score,setScore]=useState(0);const [combo,setCombo]=useState(1);const [time]=useTimer(90,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setBoard(triadBoard());setAnchor(null);setScore(0);setCombo(1);props.onScore(0);},[props.resetKey]);function choose(row:number,col:number){if(!anchor){setAnchor({row,col});return;}const rect=rectFromPoints(anchor,{row,col});const counts=[0,0,0];for(let r=rect.top;r<=rect.bottom;r++)for(let c=rect.left;c<=rect.right;c++)if(board[r][c]!==null)counts[board[r][c]!]++;setAnchor(null);if(!counts[0]||counts[0]!==counts[1]||counts[1]!==counts[2]){setCombo(1);props.onStatus(text(props.locale,`Counts ${counts.join(" / ")}`,`数量 ${counts.join(" / ")}`));return;}const next=board.map(items=>[...items]);for(let r=rect.top;r<=rect.bottom;r++)for(let c=rect.left;c<=rect.right;c++)next[r][c]=null;const random=createRandom();for(let c=0;c<9;c++){const existing=next.map(row=>row[c]).filter((value):value is number=>value!==null);while(existing.length<9)existing.push(random.int(0,2));for(let r=0;r<9;r++)next[r][c]=existing[r];}const triads=counts[0],base=[0,6,16,30,48][triads]??triads*12,total=score+Math.round(base*combo);setBoard(next);setScore(total);props.onScore(total);setCombo(Math.min(2.5,combo+.5));props.sound("score");props.onStatus(text(props.locale,`${triads} triad${triads>1?"s":""} captured`,`捕获了 ${triads} 组三色符号`));}return <div className="logic-game garden-game"><GardenHud locale={props.locale} target={text(props.locale,"Equal non-zero counts","三种符号数量相等且不为零")} time={time} extra={`${text(props.locale,"Combo","连击")} ×${combo}`}/><div className="garden-grid triad-grid">{board.flatMap((row,r)=>row.map((value,c)=><button key={`${r}-${c}`} className={`symbol-${value}`} onClick={()=>choose(r,c)} aria-label={`${r+1},${c+1}: ${symbols[value!]}`}>{symbols[value!]}</button>))}</div></div>}

function echoBoard(){const random=createRandom();const board=Array.from({length:10},()=>Array.from({length:10},()=>random.int(0,3)));board[0][0]=0;board[0][1]=1;board[0][2]=0;return board;}
function EchoPath(props:PlayableGameProps){const [board,setBoard]=useState(echoBoard);const [path,setPath]=useState<Cell[]>([]);const [locked,setLocked]=useState<Set<string>>(new Set());const [score,setScore]=useState(0);const [time]=useTimer(120,props.paused,props.resetKey,()=>props.onEnd(text(props.locale,"Time is up","时间到")));useEffect(()=>{setBoard(echoBoard());setPath([]);setLocked(new Set());setScore(0);props.onScore(0);},[props.resetKey]);function choose(row:number,col:number){if(locked.has(`${row}-${col}`))return;if(!path.length){setPath([{row,col}]);return;}const last=path.at(-1)!;if(Math.abs(last.row-row)+Math.abs(last.col-col)!==1||path.some(cell=>cell.row===row&&cell.col===col)){props.onStatus(text(props.locale,"Paths move one orthogonal cell and cannot revisit","路径只能正交相邻移动，不能重复经过格子"));return;}setPath([...path,{row,col}]);}function confirm(){if(path.length<3)return;const first=board[path[0].row][path[0].col],last=board[path.at(-1)!.row][path.at(-1)!.col],interiors=path.slice(1,-1).map(cell=>board[cell.row][cell.col]);if(first!==last||!interiors.length||interiors.some(value=>value!==interiors[0])||interiors[0]===first){props.onStatus(text(props.locale,"Invalid echo path","回声路径无效"));setPath([]);return;}const nextLocked=new Set(locked);for(const cell of path)nextLocked.add(`${cell.row}-${cell.col}`);const total=score+4+Math.max(0,path.length-3)*2;setLocked(nextLocked);setScore(total);props.onScore(total);props.sound("score");props.onStatus(text(props.locale,`Path length ${path.length} locked`,`长度为 ${path.length} 的路径已锁定`));setPath([]);}return <div className="logic-game garden-game"><GardenHud locale={props.locale} target={text(props.locale,"Matching ends, one interior symbol","端点相同，中间符号统一")} time={time} extra={`${text(props.locale,"Path length","路径长度")} ${path.length}`}/><div className="garden-grid echo-grid">{board.flatMap((row,r)=>row.map((value,c)=>{const active=path.some(cell=>cell.row===r&&cell.col===c);return <button key={`${r}-${c}`} onClick={()=>choose(r,c)} disabled={locked.has(`${r}-${c}`)} className={`symbol-${value} ${active?"selected":""} ${locked.has(`${r}-${c}`)?"locked":""}`} aria-label={`${r+1},${c+1}: ${symbols[value]}`}>{symbols[value]}</button>;}))}</div><div className="logic-actions"><button onClick={()=>setPath(path.slice(0,-1))} disabled={!path.length}>{text(props.locale,"Back","退回一步")}</button><button onClick={()=>setPath([])}>{text(props.locale,"Cancel","取消")}</button><button onClick={confirm} disabled={path.length<3}>{text(props.locale,"Confirm path","确认路径")}</button></div></div>}

function basketRound(){const random=createRandom();const a=random.int(1,20),b=random.int(1,20),target=a+b;const values=[a,b];while(values.length<6)values.push(random.int(1,20));for(let i=values.length-1;i>0;i--){const j=random.int(0,i);[values[i],values[j]]=[values[j],values[i]];}return{target,values};}
function TargetBasket(props:PlayableGameProps){const [round,setRound]=useState(1);const [data,setData]=useState(basketRound);const [selected,setSelected]=useState<number[]>([]);const [score,setScore]=useState(0);const [streak,setStreak]=useState(0);const [time,setTime]=useState(12);useEffect(()=>{setRound(1);setData(basketRound());setSelected([]);setScore(0);setStreak(0);setTime(12);props.onScore(0);},[props.resetKey]);useEffect(()=>{if(props.paused)return;const id=window.setInterval(()=>setTime(value=>{if(value<=1){window.clearInterval(id);queueMicrotask(()=>props.onEnd(text(props.locale,"Time is up","时间到")));return 0;}return value-1;}),1000);return()=>window.clearInterval(id);},[props.paused,props.locale,props.onEnd,round]);function choose(index:number){if(selected.includes(index)){setSelected(selected.filter(i=>i!==index));return;}const next=[...selected,index];setSelected(next);if(next.length<2)return;const correct=data.values[next[0]]+data.values[next[1]]===data.target;if(!correct){setTime(v=>Math.max(0,v-2));setSelected([]);setStreak(0);props.sound("fail");props.onStatus(text(props.locale,"Try another pair — 2 seconds","换一组再试，扣除 2 秒"));return;}const nextStreak=streak+1,total=score+100+time*5+Math.min(100,nextStreak*25);setScore(total);props.onScore(total);props.sound("score");if(round===12){props.onComplete(text(props.locale,"Twelve baskets complete","已完成十二个目标篮"));return;}setRound(r=>r+1);setData(basketRound());setSelected([]);setStreak(nextStreak);setTime(12);props.onStatus(text(props.locale,"Correct — next basket","回答正确，进入下一篮"));}return <div className="logic-game garden-game basket-game"><GardenHud locale={props.locale} target={`${text(props.locale,"Target","目标数")} ${data.target}`} time={time} extra={`${text(props.locale,"Round","轮次")} ${round}/12`}/><div className="basket-target" aria-hidden="true">Σ <strong>{data.target}</strong></div><div className="number-fruit">{data.values.map((value,index)=><button key={`${round}-${index}`} className={selected.includes(index)?"selected":""} onClick={()=>choose(index)} aria-label={`${text(props.locale,"Number","数字")} ${index+1}: ${value}`}>{value}</button>)}</div><p>{text(props.locale,"Choose exactly two numbers","选择两个数字，使它们的和等于目标数")}</p></div>}

type MathMode="add"|"subtract"|"multiply";
function operands(mode:MathMode){const random=createRandom();if(mode==="multiply")return{rows:Array.from({length:5},()=>random.int(2,9)),cols:Array.from({length:5},()=>random.int(2,9))};return{rows:Array.from({length:5},()=>random.int(15,49)),cols:Array.from({length:5},()=>random.int(1,14))};}
function mathAnswer(mode:MathMode,row:number,col:number){return mode==="add"?row+col:mode==="multiply"?row*col:Math.max(row,col)-Math.min(row,col);}
function MathGridSprint(props:PlayableGameProps){const [mode,setMode]=useState<MathMode>("add");const [data,setData]=useState(()=>operands("add"));const [answers,setAnswers]=useState<Record<string,string>>({});const [locked,setLocked]=useState<Set<string>>(new Set());const [wrong,setWrong]=useState(0);const [elapsed,setElapsed]=useState(0);useEffect(()=>{setMode("add");setData(operands("add"));setAnswers({});setLocked(new Set());setWrong(0);setElapsed(0);props.onScore(1250);},[props.resetKey]);useEffect(()=>{if(props.paused||locked.size===25)return;const id=window.setInterval(()=>setElapsed(value=>value+1),1000);return()=>window.clearInterval(id);},[props.paused,locked.size]);useEffect(()=>props.onScore(Math.max(1,1250-elapsed-wrong*8)),[elapsed,wrong,props]);function changeMode(next:MathMode){if(Object.keys(answers).length&&!window.confirm(text(props.locale,"Changing mode starts a new run. Continue?","切换模式会开始新一局，是否继续？")))return;setMode(next);setData(operands(next));setAnswers({});setLocked(new Set());setWrong(0);setElapsed(0);}function submit(key:string,r:number,c:number){if(Number(answers[key])===mathAnswer(mode,data.rows[r],data.cols[c])){const next=new Set(locked);next.add(key);setLocked(next);props.sound("score");props.onStatus(text(props.locale,"Correct","正确"));if(next.size===25)props.onComplete(text(props.locale,`Grid complete in ${elapsed} seconds`,`用时 ${elapsed} 秒完成方格`));}else{setWrong(v=>v+1);props.sound("fail");props.onStatus(text(props.locale,"Check the calculation","请检查计算"));}}return <div className="logic-game garden-game math-game"><div className="mode-tabs" role="group" aria-label={text(props.locale,"Math mode","运算模式")}>{(["add","subtract","multiply"] as MathMode[]).map(value=><button key={value} aria-pressed={mode===value} onClick={()=>changeMode(value)}>{text(props.locale,{add:"Addition",subtract:"Subtraction",multiply:"Multiplication"}[value],{add:"加法",subtract:"减法",multiply:"乘法"}[value])}</button>)}</div><GardenHud locale={props.locale} target={`${locked.size}/25 ${text(props.locale,"correct","已答对")}`} time={elapsed} extra={`${text(props.locale,"Errors","错误")} ${wrong}`}/><div className="math-grid" style={{gridTemplateColumns:"52px repeat(5,1fr)"}}><span>◈</span>{data.cols.map((value,i)=><b key={`c${i}`}>{value}</b>)}{data.rows.flatMap((row,r)=>[<b key={`r${r}`}>{row}</b>,...data.cols.map((_,c)=>{const key=`${r}-${c}`;return <input key={key} inputMode="numeric" aria-label={`${row} ${mode} ${data.cols[c]}`} value={answers[key]??""} readOnly={locked.has(key)} className={locked.has(key)?"correct":""} onChange={event=>setAnswers({...answers,[key]:event.target.value.replace(/\D/g,"").slice(0,3)})} onKeyDown={event=>{if(event.key==="Enter")submit(key,r,c);}} onBlur={()=>answers[key]&&submit(key,r,c)} />;})])}</div></div>}

function GardenHud({locale,target,time,extra}:{locale:PlayableGameProps["locale"];target:string;time:number;extra:string}){return <div className="garden-hud"><strong>{target}</strong><span>{text(locale,"Time","时间")} {time}s</span><small>{extra}</small></div>}
